## Imports

In [20]:
import warnings
warnings.filterwarnings("ignore")

In [21]:
import math
import os
import time
import requests
import pandas as pd
import json
import numpy as np
from pathlib import Path
from typing import Optional, Dict, List, Union
from unidecode import unidecode
import matplotlib.pyplot as plt

import pandas_gbq
from google.auth import default
from google.cloud import bigquery
from google.api_core.exceptions import NotFound

In [22]:
from funcoes_escoragem import *

## Diretório

In [23]:
BASE_DIR = Path("data")
RAW_DIR = BASE_DIR / "raw"
TRUSTED_DIR = BASE_DIR / "trusted"
ANALYTICS_DIR = BASE_DIR / "analytics"

for path in [RAW_DIR, TRUSTED_DIR, ANALYTICS_DIR]:
    path.mkdir(parents=True, exist_ok=True)

# Funil Modelos

In [24]:
project_id = 'loft-dl-fintech'

In [25]:
query = '''
WITH tb_leads AS (
  SELECT 
    rf.contract_id,
    date(rf.dt_lead) as dt_lead,
    date(cf.requested_at) as requested_at,
    date(rf.dt_proposta_iniciada) as iniciada_at,
    date(rf.dt_proposta_enviada) as enviada_at,
    date(rf.activated_at) as activated_at,
    date(rf.cancelled_at) as cancelled_at,
    date(rf.dt_saida) as dt_saida,
    cf.tipo_contrato,
    rd.product_nm,
    cf.modeloBlend,
    cf.bureau_nm,
    cf.modelo_blend,
    case when cf.modeloBlend in ('BLEND_4', 'BVS_CUSTOM_V2', 'HFT1') then 'BLEND4'
         when cf.bureau_nm in ('BLEND_4', 'BVS_CUSTOM_V2', 'HFT1') then 'BLEND4'
         when cf.modeloBlend in ('BLEND3_3', 'BVS_CUSTOM', 'HVA4') then 'BLEND3'
         when cf.bureau_nm in ('BLEND3_3', 'BVS_CUSTOM', 'HVA4') then 'BLEND3'
         else modeloBlend end as bureau_nm_ajust,
    case when cf.modeloBlend in ('BVS_CUSTOM_V2', 'HFT1', 'BVS_CUSTOM', 'HVA4') then 1
         when cf.bureau_nm in ('BVS_CUSTOM_V2', 'HFT1', 'BVS_CUSTOM', 'HVA4') then 1 else 0 end as is_fallback,
    cast(rf.total_rental_value_informed_nr as FLOAT64) as total_rental_value_informed_nr,
    cast(rf.rental_value_nr as FLOAT64) as rental_value_nr,
    cf.agency_id,
    cf.contract_city_nm,
    cf.person_age,
    cf.qtd_proponentes,
    cf.score_imobiliaria,
    cf.person_restriction_total_value,
    ca.bvs_cust_score_nr,
    ca.blend_regressao_predict_nr,
    cf.rating_score_ds,
    cf.person_deemed_income,
    rd.pre_analysis_result,
    rd.lead_elegivel,
    rd.proposta_iniciada,
    rd.proposta_enviada,
    rd.proposta_aprovada,
    rd.proposta_ativada,
    rd.is_activeted
  FROM loft-dl-fintech.cp_gold.requests_fact AS rf
  LEFT JOIN loft-dl-fintech.cp_gold.requests_dim AS rd
    ON rf.contract_id = rd.contract_id
  LEFT JOIN loft-dl-fintech.cp_gold.credit_fact AS cf
    ON rf.contract_id = cf.contract_id
  LEFT JOIN loft-dl-fintech.cp_silver.int_credit_analyses AS ca
    ON rf.contract_id = ca.contract_id
  WHERE cf.tipo_contrato = 'PF'
),
first_defaults AS (
  SELECT
    contract_id
    , DATE(MIN(pendency_created_at)) AS first_comunicacao_date
    , DATE(MIN(pendency_at)) AS first_competencia_date
  FROM loft-dl-fintech.cp_gold.watchlist_fact
  WHERE pendency_type = "Inadimplência"
  GROUP BY contract_id
)
SELECT
  l.*
  , fd.first_comunicacao_date
  , fd.first_competencia_date
FROM tb_leads AS l
LEFT JOIN first_defaults as fd
  on l.contract_id = fd.contract_id
  and l.activated_at is not null
where 1=1
    and date(l.requested_at) >= date('2026-07-01')
    and date(l.requested_at) < date(current_date())
'''

In [26]:
df_funil = pandas_gbq.read_gbq(query, project_id=project_id)
df_funil

Downloading: 100%|██████████|

,contract_id,dt_lead,requested_at,iniciada_at,enviada_at,activated_at,cancelled_at,dt_saida,tipo_contrato,product_nm,...,person_deemed_income,pre_analysis_result,lead_elegivel,proposta_iniciada,proposta_enviada,proposta_aprovada,proposta_ativada,is_activeted,first_comunicacao_date,first_competencia_date
0,4562109,2026-08-25,2026-08-25,NaT,NaT,NaT,2026-08-25,NaT,PF,None,...,1781.000000000,REPROVAR,False,False,False,False,False,False,NaT,NaT
1,4558544,2026-08-25,2026-08-25,NaT,NaT,NaT,2026-08-25,NaT,PF,None,...,0E-9,REPROVAR,False,False,False,False,False,False,NaT,NaT
2,4558139,2026-08-25,2026-08-25,NaT,NaT,NaT,2026-08-25,NaT,PF,None,...,3356.500000000,REPROVAR,False,False,False,False,False,False,NaT,NaT
3,4560024,2026-08-25,2026-08-25,NaT,NaT,NaT,2026-08-25,NaT,PF,None,...,5343.000000000,REPROVAR,False,False,False,False,False,False,NaT,NaT
4,4557978,2026-08-25,2026-08-25,NaT,NaT,NaT,2026-08-25,NaT,PF,None,...,0E-9,REPROVAR,False,False,False,False,False,False,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252043,4324175,2026-07-02,2026-07-02,2026-07-02,2026-07-02,NaT,NaT,NaT,PF,Smart Plus,...,2740.000000000,APROVAR,True,True,True,True,False,False,NaT,NaT
252044,4324321,2026-07-02,2026-07-02,2026-07-02,NaT,NaT,NaT,NaT,PF,Smart Plus,...,4589.500000000,APROVAR,True,True,False,False,False,False,NaT,NaT
252045,4323185,2026-07-02,2026-07-02,2026-07-02,2026-07-02,2026-07-02,NaT,NaT,PF,Smart Plus,...,2740.000000000,APROVAR,True,True,True,True,True,True,NaT,NaT
252046,4327595,2026-07-02,2026-07-02,2026-07-06,2026-07-06,2026-07-06,NaT,NaT,PF,Fit,...,1370.000000000,APROVAR,True,True,True,True,True,True,NaT,NaT
252047,4326667,2026-07-02,2026-07-02,2026-07-02,2026-07-02,2026-07-02,NaT,NaT,PF,Smart,...,9795.500000000,APROVAR,True,True,True,True,True,True,NaT,NaT

In [27]:
df_funil.groupby("bureau_nm_ajust", dropna=False).size()

bureau_nm_ajust
BLEND3                  111034
BLEND3_4                 61725
BLEND4                   77973
BLEND_REGRESSAO_2026      1278
NaN                         38
dtype: int64

In [28]:
df_funil.groupby("bureau_nm", dropna=False).size()

bureau_nm
                            22
BLEND3_3                104779
BLEND3_4                 59553
BLEND_4                  73207
BLEND_REGRESSAO_2026      1188
BVS_CUSTOM                 421
BVS_CUSTOM_V2              937
HFT1                       624
HVA3                      9644
HVA4                      1635
NaN                         38
dtype: int64

In [29]:
df_funil.groupby("bureau_nm_ajust", dropna=False).size()

bureau_nm_ajust
BLEND3                  111034
BLEND3_4                 61725
BLEND4                   77973
BLEND_REGRESSAO_2026      1278
NaN                         38
dtype: int64

In [30]:
df_funil.groupby("modeloBlend", dropna=False).size()

modeloBlend
BLEND3_3                110254
BLEND3_4                 62298
BLEND_4                  77676
BLEND_REGRESSAO_2026      1485
BVS_CUSTOM_V2              165
HFT1                       132
NaN                         38
dtype: int64

In [31]:
bvs = pd.to_numeric(df_funil["bvs_cust_score_nr"], errors="coerce")
score = pd.to_numeric(df_funil["blend_regressao_predict_nr"], errors="coerce")

conditions = [
    bvs <= 334,                         # corte customizado BVS → E
    score.between(763, 1000),           # 763 – 1000
    score.between(704, 762),            # 704 – 762
    score.between(653, 703),            # 653 – 703
    score.between(607, 652),            # 607 – 652
    score.between(562, 606),            # 562 – 606
    score.between(520, 561),            # 520 – 561
    score.between(480, 519),            # 480 – 519
    score.between(443, 479),            # 443 – 479
    score.between(408, 442),            # 408 – 442
    score.between(375, 407),            # 375 – 407
    score.between(343, 374),            # 343 – 374
    score.between(307, 342),            # 307 – 342
    score.between(0, 306),              # 0 – 306
]

choices = [
    "E.BVS",      # override BVS ≤ 334
    "1.A+",
    "2.A",
    "3.A",
    "4.B+",
    "5.B+",
    "6.B",
    "7.B",
    "8.C",
    "9.D+",
    "10.D",
    "11.D",
    "E-1.E",
    "E-2.E",
]

df_funil["rating_cl_pol_blend4"] = np.select(conditions, choices, default=None)

In [32]:
bvs = pd.to_numeric(df_funil["bvs_cust_score_nr"], errors="coerce")
score = pd.to_numeric(df_funil["blend_regressao_predict_nr"], errors="coerce")

conditions = [
    bvs <= 334,                         # corte customizado BVS → E
    score.between(763, 1000),           # 763 – 1000
    score.between(704, 762),            # 704 – 762
    score.between(653, 703),            # 653 – 703
    score.between(607, 652),            # 607 – 652
    score.between(562, 606),            # 562 – 606
    score.between(520, 561),            # 520 – 561
    score.between(480, 519),            # 480 – 519
    score.between(443, 479),            # 443 – 479
    score.between(408, 442),            # 408 – 442
    score.between(375, 407),            # 375 – 407
    score.between(343, 374),            # 343 – 374
    score.between(307, 342),            # 307 – 342
    score.between(0, 306),              # 0 – 306
]

choices = [
    "9.E-BVS",      # override BVS ≤ 334
    "1.A+",
    "2.A",
    "2.A",
    "3.B+",
    "3.B+",
    "4.B",
    "4.B",
    "5.C",
    "6.D+",
    "7.D",
    "7.D",
    "8.E",
    "8.E",
]

df_funil["rating_pol_blend4"] = np.select(conditions, choices, default=None)
df_funil["rating_pol_blend4"] = df_funil["rating_pol_blend4"].fillna("N/I")

In [33]:
df_funil.groupby("rating_pol_blend4", dropna=False).size()

rating_pol_blend4
1.A+        6640
2.A        22053
3.B+       25698
4.B        26708
5.C        13314
6.D+       13592
7.D        27300
8.E        66145
9.E-BVS     7710
N/I        42888
dtype: int64

In [34]:
df_funil.to_csv(ANALYTICS_DIR/"df_funil_blend4.csv", index=False)

In [35]:
df_funil[df_funil["contract_id"]==4358668][["contract_id", "modeloBlend", "bureau_nm", "modelo_blend", "bureau_nm_ajust", "is_fallback"]]

,contract_id,modeloBlend,bureau_nm,modelo_blend,bureau_nm_ajust,is_fallback
9607,4358668,BLEND_4,BLEND3_3,BLEND_4,BLEND4,0

In [36]:
df_blend4_dev = pd.read_csv(ANALYTICS_DIR/"df_predict_blend4.csv")

In [37]:
df_blend4_dev.columns.tolist()

['CPF_CNPJ',
 'contract_id',
 'requested_at',
 'data_ultima_consulta',
 'qtd_proponentes',
 'score_imobiliaria',
 'model',
 'id_consulta',
 'id_funcionalidade',
 'documento',
 'rating',
 'result',
 'message_rendaConsiderada',
 'income',
 'message_rendaUtilizada',
 'message_fatorCorrecaoRenda',
 'message_limiteCalculadoContrato',
 'qtde_restricoes__consulta_realizada',
 'message_restricoesPorModalidadeContrato',
 'message_regra_estouro_limite',
 'message_valorRestricaoTotal',
 'message_regua',
 'message_score',
 'message_blendRegressaoPredict',
 'message_decisao',
 'message_classificacao',
 'message_classificacaoInquilino',
 'message_existeErroSerasa',
 'message_existeErroPowerCurve',
 'message_existeErroBvsCustom',
 'message_motor',
 'message_regras_situacao_cadastral_serasa',
 'message_scores_BVS_CUSTOM',
 'message_scores_HVA4',
 'message_scores_BLEND3_3',
 'message_ratings_BVS_CUSTOM',
 'message_ratings_HVA4',
 'message_ratings_BLEND3_3',
 'message_feature_flags_analiseAutomaticaDeCredito',
 'message_feature_flags_modeloBlend',
 'flag_tem__contratos_anteriores',
 'flag_teve_boleto_atrasado__contratos_anteriores',
 'city_pc4_mais_100_contratos__pc_categorias',
 'agency_pc4_mais_100_contratos__pc_categorias',
 'message_scores_HVA3',
 'message_ratings_HVA3',
 'message_scores_BLEND_REGRESSAO_2026',
 'message_ratings_BLEND_REGRESSAO_2026',
 'score_proposto__bvs',
 'SERASA_CHSV5',
 'message_ratings_BLEND_4',
 'message_scores_BLEND3_4',
 'message_ratings_BLEND3_4',
 'message_ratings_HFT1',
 'message_ratings_BVS_CUSTOM_V2',
 'message_flexPricingIncentive_incentive_pricing',
 'message_flexPricingIncentive_real_estate_agency_id',
 'message_flexPricingIncentive_constraints_override',
 'message_flexPricingIncentive_version',
 'message_flexPricingIncentive_constraints_override_exit_cost_multiplier',
 'message_flexPricingIncentive_constraints_override_rent_coverage_multiplier',
 'message_flexPricingIncentive_constraints_override_commission_percent',
 'message_dadosAusentes_0',
 'message_dadosAusentes_1',
 'message_dadosAusentes_3',
 'pessoa_nome',
 'pessoa_documento',
 'pessoa_classificacao',
 'pessoa_tipoPessoa',
 'age',
 'pessoa_dt_nascimento',
 'pessoa_rendaConsideradaPessoa',
 'pessoa_rendaUtilizada',
 'pessoa_fatorCorrecaoRenda',
 'pessoa_limiteCalculadoPessoa',
 'pessoa_qtdeRestricoes',
 'pessoa_valorTotalRestricao',
 'pessoa_situacao_cadastral_serasa',
 'pessoa_existeErroSerasa',
 'pessoa_existeErroPowerCurve',
 'pessoa_existeErroBvsCustom',
 'pessoa_restricoesPorModalidade',
 'pessoa_nomeSerasa',
 'pessoa_rendaPresumidaSerasa',
 'pessoa_scores_BVS_CUSTOM',
 'pessoa_scores_HVA4',
 'pessoa_scores_BLEND3_3',
 'pessoa_ratings_BVS_CUSTOM',
 'pessoa_ratings_HVA4',
 'pessoa_ratings_BLEND3_3',
 'pessoa_anotacoesFinanceirasSerasa_Pefin_DataPrimeiraOcorrenciaPefin',
 'pessoa_anotacoesFinanceirasSerasa_Pefin_DataUltimaOcorrenciaPefin',
 'pessoa_anotacoesFinanceirasSerasa_Pefin_QuantidadeTotalPefin',
 'pessoa_anotacoesFinanceirasSerasa_Pefin_ValorTotalPefin',
 'pessoa_anotacoesFinanceirasSerasa_Refin_DataPrimeiraOcorrenciaRefin',
 'pessoa_anotacoesFinanceirasSerasa_Refin_DataUltimaOcorrenciaRefin',
 'pessoa_anotacoesFinanceirasSerasa_Refin_QuantidadeTotalRefin',
 'pessoa_anotacoesFinanceirasSerasa_Refin_ValorTotalRefin',
 'pessoa_anotacoesFinanceirasSerasa_Acao_DataPrimeiraAcao',
 'pessoa_anotacoesFinanceirasSerasa_Acao_DataUltimaAcao',
 'pessoa_anotacoesFinanceirasSerasa_Acao_QuantidadeTotalAcao',
 'pessoa_anotacoesFinanceirasSerasa_Acao_ValorTotalAcao',
 'pessoa_anotacoesFinanceirasSerasa_Protesto_DataPrimeiraOcorrenciaProtesto',
 'pessoa_anotacoesFinanceirasSerasa_Protesto_DataUltimaOcorrenciaProtesto',
 'pessoa_anotacoesFinanceirasSerasa_Protesto_QuantidadeTotalProtesto',
 'pessoa_anotacoesFinanceirasSerasa_Protesto_TipoMoeda',
 'pessoa_anotacoesFinanceirasSerasa_Protesto_ValorTotalProtesto',
 'pessoa_anotacoesFinanceirasSerasa_DividaVencida_DataPrimeiraOcorrenciaDividasVencidas',
 'pessoa_anotacoesFinanceirasSerasa_DividaVencida_DataUltimaOcorrenciaDividasVencidas',
 'pessoa_anotacoesFinanceirasSerasa_DividaVencida_QuantidadeTotalDividasVencidas',
 'pessoa_anotacoesFinanceirasSerasa_DividaVencida_ValorTotalDividasVencidas',
 'pessoa_anotacoesFinanceirasSerasa_ChequeSemFundos_QuantidadeCCF',
 'pessoa_anotacoesFinanceirasSerasa_ChequeSemFundos_ValorTotalCCF',
 'pessoa_anotacoesFinanceirasSerasa_PendenciasPagamentoPF',
 'pessoa_anotacoesFinanceirasSerasa_AcoesJudiciaisPF',
 'pessoa_anotacoesFinanceirasSerasa_ProtestosPF',
 'pessoa_anotacoesFinanceirasSerasa_DividasVencidasPF',
 'pessoa_anotacoesFinanceirasSerasa_ChequesSemFundosPF',
 'pessoa_scores_HVA3',
 'pessoa_ratings_HVA3',
 'pessoa_scores_BLEND_REGRESSAO_2026',
 'pessoa_ratings_BLEND_REGRESSAO_2026',
 'pessoa_anotacoesFinanceirasSerasa',
 'pessoa_scores_BVS_CUSTOM_V2',
 'pessoa_scores_HFT1',
 'pessoa_ratings_BLEND_4',
 'pessoa_scores_BLEND3_4',
 'pessoa_ratings_BLEND3_4',
 'pessoa_ratings_HFT1',
 'pessoa_ratings_BVS_CUSTOM_V2',
 'request_matchmaking_on',
 'request_imovel_codigo_cidade_ibge',
 'request_pessoa_principal_nome',
 'request_principalDocument',
 'request_imobiliariaId',
 'request_idExterno',
 'request_rating',
 'rental_value',
 'property_type',
 'request_modeloBlend',
 'request_rendaConsideradaContrato',
 'request_valorRestricaoTotal',
 'request_quantidadeRestricoesContrato',
 'request_nome',
 'request_dtNascimento',
 'request_situacaoCadastralSerasa',
 'request_existeErroPowerCurve',
 'request_scoreImobiliaria',
 'request_blendPredict',
 'request_existingContractDebts_qtdeImoveis',
 'request_existingContractDebts_qtdeDividas',
 'request_existingContractDebts_saldoReceber',
 'request_existingContractDebts_taxaCredpago',
 'request_scores_BVS_CUSTOM_V2',
 'request_scores_HFT1',
 'request_blend3Variables_hasPreviousContracts',
 'request_blend3Variables_hadOverdueInvoiceInPreviousContracts',
 'request_blend3Variables_cityPc4HistoryOver100Contracts',
 'request_blend3Variables_realEstatePc4HistoryOver100Contracts',
 'request_fallbackPolicyResult',
 'request_ratingPoliciesResult',
 'request_fallbackPolicyResult_status',
 'request_fallbackPolicyResult_decision',
 'qtde_pefin',
 'valor_pefin_total',
 'modalidades_pefin',
 'REGRA_BLEND_4',
 'SCORE_BVS',
 'SCORE_SERASA',
 'RENDA',
 'income_commitment',
 'city_pc4_mais_100_contratos__pc_categorias_is_null',
 'agency_pc4_mais_100_contratos__pc_categorias_is_null',
 'score_proposto__bvs__normalized4_1',
 'SERASA_CHSV5__normalized4_1',
 'age__normalized4_1',
 'qtde_restricoes__consulta_realizada__normalized4_1',
 'income_commitment__normalized4_1',
 'agency_pc4_mais_100_contratos__pc_categorias__normalized4_1',
 'city_pc4_mais_100_contratos__pc_categorias__normalized4_1',
 'pred_blend4_1',
 'pred_blend4_1_to_score',
 'rating_manual_blend4',
 'rating_json_blend4',
 'rating_cl_pol_blend4']

In [38]:
df_blend4_dev[df_blend4_dev["contract_id"]==4358668][["contract_id", "model", "message_decisao", "message_scores_HVA4", "message_ratings_BVS_CUSTOM", "pessoa_scores_HVA4"]]

,contract_id,model,message_decisao,message_scores_HVA4,message_ratings_BVS_CUSTOM,pessoa_scores_HVA4
77166,4358668,BLEND3_3,BLEND3_3,870.0,A,870.0