## Imports

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import math
import os
import time
import requests
import pandas as pd
import json
import numpy as np
from pathlib import Path
from typing import Optional, Dict, List, Union
from unidecode import unidecode
import matplotlib.pyplot as plt

import pandas_gbq
from google.auth import default
from google.cloud import bigquery
from google.api_core.exceptions import NotFound

In [3]:
from funcoes_escoragem import *

## Diretório

In [4]:
BASE_DIR = Path("data")
RAW_DIR = BASE_DIR / "raw"
TRUSTED_DIR = BASE_DIR / "trusted"
ANALYTICS_DIR = BASE_DIR / "analytics"

for path in [RAW_DIR, TRUSTED_DIR, ANALYTICS_DIR]:
    path.mkdir(parents=True, exist_ok=True)

# Funil Modelos

In [5]:
project_id = 'loft-dl-fintech'

In [6]:
query = '''
WITH tb_leads AS (
  SELECT 
    rf.contract_id,
    date(rf.dt_lead) as dt_lead,
    date(cf.requested_at) as requested_at,
    date(rf.dt_proposta_iniciada) as iniciada_at,
    date(rf.dt_proposta_enviada) as enviada_at,
    date(rf.activated_at) as activated_at,
    date(rf.cancelled_at) as cancelled_at,
    date(rf.dt_saida) as dt_saida,
    cf.tipo_contrato,
    rd.product_nm,
    cf.modeloBlend,
    cf.bureau_nm,
    cf.modelo_blend,
    case when cf.modeloBlend in ('BLEND_4', 'BVS_CUSTOM_V2', 'HFT1') then 'BLEND4'
         when cf.bureau_nm in ('BLEND_4', 'BVS_CUSTOM_V2', 'HFT1') then 'BLEND4'
         when cf.modeloBlend in ('BLEND3_3', 'BVS_CUSTOM', 'HVA4') then 'BLEND3'
         when cf.bureau_nm in ('BLEND3_3', 'BVS_CUSTOM', 'HVA4') then 'BLEND3'
         else modeloBlend end as bureau_nm_ajust,
    case when cf.modeloBlend in ('BVS_CUSTOM_V2', 'HFT1', 'BVS_CUSTOM', 'HVA4') then 1
         when cf.bureau_nm in ('BVS_CUSTOM_V2', 'HFT1', 'BVS_CUSTOM', 'HVA4') then 1 else 0 end as is_fallback,
    cast(rf.total_rental_value_informed_nr as FLOAT64) as total_rental_value_informed_nr,
    cast(rf.rental_value_nr as FLOAT64) as rental_value_nr,
    cf.agency_id,
    cf.contract_city_nm,
    cf.person_age,
    cf.qtd_proponentes,
    cf.score_imobiliaria,
    cf.person_restriction_total_value,
    ca.bvs_cust_score_nr,
    ca.blend_regressao_predict_nr,
    cf.rating_score_ds,
    cf.person_deemed_income,
    rd.pre_analysis_result,
    rd.lead_elegivel,
    rd.proposta_iniciada,
    rd.proposta_enviada,
    rd.proposta_aprovada,
    rd.proposta_ativada,
    rd.is_activeted
  FROM loft-dl-fintech.cp_gold.requests_fact AS rf
  LEFT JOIN loft-dl-fintech.cp_gold.requests_dim AS rd
    ON rf.contract_id = rd.contract_id
  LEFT JOIN loft-dl-fintech.cp_gold.credit_fact AS cf
    ON rf.contract_id = cf.contract_id
  LEFT JOIN loft-dl-fintech.cp_silver.int_credit_analyses AS ca
    ON rf.contract_id = ca.contract_id
  WHERE cf.tipo_contrato = 'PF'
),
first_defaults AS (
  SELECT
    contract_id
    , DATE(MIN(pendency_created_at)) AS first_comunicacao_date
    , DATE(MIN(pendency_at)) AS first_competencia_date
  FROM loft-dl-fintech.cp_gold.watchlist_fact
  WHERE pendency_type = "Inadimplência"
  GROUP BY contract_id
)
SELECT
  l.*
  , fd.first_comunicacao_date
  , fd.first_competencia_date
FROM tb_leads AS l
LEFT JOIN first_defaults as fd
  on l.contract_id = fd.contract_id
  and l.activated_at is not null
where 1=1
    and date(l.requested_at) >= date('2026-07-01')
    and date(l.requested_at) < date(current_date())
'''

In [7]:
df_funil = pandas_gbq.read_gbq(query, project_id=project_id)
df_funil

Downloading: 100%|██████████|

,contract_id,dt_lead,requested_at,iniciada_at,enviada_at,activated_at,cancelled_at,dt_saida,tipo_contrato,product_nm,...,person_deemed_income,pre_analysis_result,lead_elegivel,proposta_iniciada,proposta_enviada,proposta_aprovada,proposta_ativada,is_activeted,first_comunicacao_date,first_competencia_date
0,4507913,2026-08-13,2026-08-13,NaT,NaT,NaT,NaT,NaT,PF,None,...,9110.500000000,APROVAR,True,False,False,False,False,False,NaT,NaT
1,4504802,2026-08-13,2026-08-13,NaT,NaT,NaT,NaT,NaT,PF,None,...,3767.500000000,DERIVAR,True,False,False,False,False,False,NaT,NaT
2,4510547,2026-08-13,2026-08-13,NaT,NaT,NaT,NaT,NaT,PF,None,...,67267.000000000,APROVAR,True,False,False,False,False,False,NaT,NaT
3,4507027,2026-08-13,2026-08-13,NaT,NaT,NaT,NaT,NaT,PF,None,...,1233.000000000,APROVAR,True,False,False,False,False,False,NaT,NaT
4,4509995,2026-08-13,2026-08-13,NaT,NaT,NaT,NaT,NaT,PF,None,...,1918.000000000,APROVAR,True,False,False,False,False,False,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495871,4381509,2026-07-16,2026-07-16,2026-07-16,NaT,NaT,2026-08-16,NaT,PF,Fit,...,2397.500000000,DERIVAR,True,True,False,False,False,False,NaT,NaT
495872,4383495,2026-07-16,2026-07-16,2026-07-27,2026-07-27,2026-07-27,NaT,NaT,PF,Smart,...,5754.000000000,APROVAR,True,True,True,True,True,True,NaT,NaT
495873,4383212,2026-07-16,2026-07-16,2026-07-24,NaT,NaT,2026-08-16,NaT,PF,Up,...,4041.500000000,APROVAR,True,True,False,False,False,False,NaT,NaT
495874,4381604,2026-07-16,2026-07-16,2026-07-16,NaT,NaT,2026-08-16,NaT,PF,Flex,...,2603.000000000,APROVAR,True,True,False,False,False,False,NaT,NaT
495875,4383977,2026-07-16,2026-07-16,2026-07-16,NaT,NaT,2026-08-16,NaT,PF,Flex,...,5000.500000000,DERIVAR,True,True,False,False,False,False,NaT,NaT

In [8]:
df_funil.groupby("bureau_nm_ajust", dropna=False).size()

bureau_nm_ajust
BLEND3                  111237
BLEND3_4                109484
BLEND4                  273658
BLEND_REGRESSAO_2026      1278
NaN                        219
dtype: int64

In [9]:
df_funil.groupby("bureau_nm", dropna=False).size()

bureau_nm
                            37
BLEND3_3                104775
BLEND3_4                105881
BLEND_4                 257694
BLEND_REGRESSAO_2026      1188
BVS_CUSTOM                 465
BVS_CUSTOM_V2             3770
HFT1                      1089
HVA3                     18955
HVA4                      1803
NaN                        219
dtype: int64

In [10]:
df_funil.groupby("bureau_nm_ajust", dropna=False).size()

bureau_nm_ajust
BLEND3                  111237
BLEND3_4                109484
BLEND4                  273658
BLEND_REGRESSAO_2026      1278
NaN                        219
dtype: int64

In [11]:
df_funil.groupby("modeloBlend", dropna=False).size()

modeloBlend
BLEND3_3                110250
BLEND3_4                110264
BLEND_4                 273361
BLEND_REGRESSAO_2026      1485
BVS_CUSTOM_V2              165
HFT1                       132
NaN                        219
dtype: int64

In [12]:
bvs = pd.to_numeric(df_funil["bvs_cust_score_nr"], errors="coerce")
score = pd.to_numeric(df_funil["blend_regressao_predict_nr"], errors="coerce")

conditions = [
    bvs <= 334,                         # corte customizado BVS → E
    score.between(763, 1000),           # 763 – 1000
    score.between(704, 762),            # 704 – 762
    score.between(653, 703),            # 653 – 703
    score.between(607, 652),            # 607 – 652
    score.between(562, 606),            # 562 – 606
    score.between(520, 561),            # 520 – 561
    score.between(480, 519),            # 480 – 519
    score.between(443, 479),            # 443 – 479
    score.between(408, 442),            # 408 – 442
    score.between(375, 407),            # 375 – 407
    score.between(343, 374),            # 343 – 374
    score.between(307, 342),            # 307 – 342
    score.between(0, 306),              # 0 – 306
]

choices = [
    "E.BVS",      # override BVS ≤ 334
    "1.A+",
    "2.A",
    "3.A",
    "4.B+",
    "5.B+",
    "6.B",
    "7.B",
    "8.C",
    "9.D+",
    "10.D",
    "11.D",
    "E-1.E",
    "E-2.E",
]

df_funil["rating_cl_pol_blend4"] = np.select(conditions, choices, default=None)

In [13]:
bvs = pd.to_numeric(df_funil["bvs_cust_score_nr"], errors="coerce")
score = pd.to_numeric(df_funil["blend_regressao_predict_nr"], errors="coerce")

conditions = [
    bvs <= 334,                         # corte customizado BVS → E
    score.between(763, 1000),           # 763 – 1000
    score.between(704, 762),            # 704 – 762
    score.between(653, 703),            # 653 – 703
    score.between(607, 652),            # 607 – 652
    score.between(562, 606),            # 562 – 606
    score.between(520, 561),            # 520 – 561
    score.between(480, 519),            # 480 – 519
    score.between(443, 479),            # 443 – 479
    score.between(408, 442),            # 408 – 442
    score.between(375, 407),            # 375 – 407
    score.between(343, 374),            # 343 – 374
    score.between(307, 342),            # 307 – 342
    score.between(0, 306),              # 0 – 306
]

choices = [
    "9.E-BVS",      # override BVS ≤ 334
    "1.A+",
    "2.A",
    "2.A",
    "3.B+",
    "3.B+",
    "4.B",
    "4.B",
    "5.C",
    "6.D+",
    "7.D",
    "7.D",
    "8.E",
    "8.E",
]

df_funil["rating_pol_blend4"] = np.select(conditions, choices, default=None)
df_funil["rating_pol_blend4"] = df_funil["rating_pol_blend4"].fillna("N/I")

In [14]:
df_funil.groupby("rating_pol_blend4", dropna=False).size()

rating_pol_blend4
1.A+        16253
2.A         43909
3.B+        48516
4.B         51033
5.C         25929
6.D+        26606
7.D         54175
8.E        134379
9.E-BVS      9919
N/I         85157
dtype: int64

In [15]:
df_funil.to_csv(ANALYTICS_DIR/"df_funil_blend4.csv", index=False)

In [16]:
df_funil[df_funil["contract_id"]==4358668][["contract_id", "modeloBlend", "bureau_nm", "modelo_blend", "bureau_nm_ajust", "is_fallback"]]

,contract_id,modeloBlend,bureau_nm,modelo_blend,bureau_nm_ajust,is_fallback
137454,4358668,BLEND_4,BLEND3_3,BLEND_4,BLEND4,0

In [17]:
df_blend4_dev = pd.read_csv(ANALYTICS_DIR/"df_predict_blend4.csv")

In [18]:
df_blend4_dev.columns.tolist()

['CPF_CNPJ',
 'contract_id',
 'requested_at',
 'data_ultima_consulta',
 'qtd_proponentes',
 'codigo_cidade_ibge',
 'score_imobiliaria',
 'model',
 'id_consulta',
 'id_funcionalidade',
 'documento',
 'rating',
 'result',
 'message_rendaConsiderada',
 'income',
 'message_rendaUtilizada',
 'message_fatorCorrecaoRenda',
 'message_limiteCalculadoContrato',
 'qtde_restricoes__consulta_realizada',
 'message_restricoesPorModalidadeContrato',
 'message_regra_estouro_limite',
 'message_valorRestricaoTotal',
 'message_regua',
 'message_score',
 'message_blendRegressaoPredict',
 'message_decisao',
 'message_classificacao',
 'message_existeErroSerasa',
 'message_existeErroPowerCurve',
 'message_existeErroBvsCustom',
 'message_motor',
 'message_regras_situacao_cadastral_serasa',
 'message_scores_HVA3',
 'message_ratings_HVA3',
 'message_feature_flags_analiseAutomaticaDeCredito',
 'message_feature_flags_modeloBlend',
 'message_flexPricingIncentive_incentive_pricing',
 'message_flexPricingIncentive_real_estate_agency_id',
 'message_flexPricingIncentive_constraints_override',
 'message_flexPricingIncentive_version',
 'message_valorAcaoJudicialTotal',
 'message_scores_HVA4',
 'message_ratings_HVA4',
 'message_feature_flags_enableCpCreditPolicies',
 'flag_tem__contratos_anteriores',
 'flag_teve_boleto_atrasado__contratos_anteriores',
 'city_pc4_mais_100_contratos__pc_categorias',
 'agency_pc4_mais_100_contratos__pc_categorias',
 'message_scores_BVS_CUSTOM',
 'message_scores_BLEND3_3',
 'message_ratings_BVS_CUSTOM',
 'message_ratings_BLEND3_3',
 'message_scores_BLEND3_4',
 'message_ratings_BLEND3_4',
 'message_flexPricingIncentive_constraints_override_exit_cost_multiplier',
 'message_flexPricingIncentive_constraints_override_rent_coverage_multiplier',
 'message_flexPricingIncentive_constraints_override_commission_percent',
 'message_dadosAusentes_0',
 'message_dadosAusentes_1',
 'message_dadosAusentes_3',
 'score_proposto__bvs',
 'SERASA_CHSV5',
 'message_ratings_BLEND_4',
 'message_ratings_BVS_CUSTOM_V2',
 'message_ratings_HFT1',
 'message_scores_BLEND_REGRESSAO_2026',
 'message_ratings_BLEND_REGRESSAO_2026',
 'message_dadosAusentes_2',
 'pessoa_nome',
 'pessoa_documento',
 'pessoa_classificacao',
 'pessoa_tipoPessoa',
 'age',
 'pessoa_dt_nascimento',
 'pessoa_rendaConsideradaPessoa',
 'pessoa_rendaUtilizada',
 'pessoa_fatorCorrecaoRenda',
 'pessoa_limiteCalculadoPessoa',
 'pessoa_qtdeRestricoes',
 'pessoa_valorTotalRestricao',
 'pessoa_situacao_cadastral_serasa',
 'pessoa_existeErroSerasa',
 'pessoa_existeErroPowerCurve',
 'pessoa_existeErroBvsCustom',
 'pessoa_restricoesPorModalidade',
 'pessoa_nomeSerasa',
 'pessoa_rendaPresumidaSerasa',
 'pessoa_scores_HVA3',
 'pessoa_ratings_HVA3',
 'pessoa_anotacoesFinanceirasSerasa_Pefin_DataPrimeiraOcorrenciaPefin',
 'pessoa_anotacoesFinanceirasSerasa_Pefin_DataUltimaOcorrenciaPefin',
 'pessoa_anotacoesFinanceirasSerasa_Pefin_QuantidadeTotalPefin',
 'pessoa_anotacoesFinanceirasSerasa_Pefin_ValorTotalPefin',
 'pessoa_anotacoesFinanceirasSerasa_Refin_DataPrimeiraOcorrenciaRefin',
 'pessoa_anotacoesFinanceirasSerasa_Refin_DataUltimaOcorrenciaRefin',
 'pessoa_anotacoesFinanceirasSerasa_Refin_QuantidadeTotalRefin',
 'pessoa_anotacoesFinanceirasSerasa_Refin_ValorTotalRefin',
 'pessoa_anotacoesFinanceirasSerasa_Acao_DataPrimeiraAcao',
 'pessoa_anotacoesFinanceirasSerasa_Acao_DataUltimaAcao',
 'pessoa_anotacoesFinanceirasSerasa_Acao_QuantidadeTotalAcao',
 'pessoa_anotacoesFinanceirasSerasa_Acao_ValorTotalAcao',
 'pessoa_anotacoesFinanceirasSerasa_Protesto_DataPrimeiraOcorrenciaProtesto',
 'pessoa_anotacoesFinanceirasSerasa_Protesto_DataUltimaOcorrenciaProtesto',
 'pessoa_anotacoesFinanceirasSerasa_Protesto_QuantidadeTotalProtesto',
 'pessoa_anotacoesFinanceirasSerasa_Protesto_TipoMoeda',
 'pessoa_anotacoesFinanceirasSerasa_Protesto_ValorTotalProtesto',
 'pessoa_anotacoesFinanceirasSerasa_DividaVencida_DataPrimeiraOcorrenciaDividasVencidas',
 'pessoa_anotacoesFinanceirasSerasa_DividaVencida_DataUltimaOcorrenciaDividasVencidas',
 'pessoa_anotacoesFinanceirasSerasa_DividaVencida_QuantidadeTotalDividasVencidas',
 'pessoa_anotacoesFinanceirasSerasa_DividaVencida_ValorTotalDividasVencidas',
 'pessoa_anotacoesFinanceirasSerasa_ChequeSemFundos_QuantidadeCCF',
 'pessoa_anotacoesFinanceirasSerasa_ChequeSemFundos_ValorTotalCCF',
 'pessoa_anotacoesFinanceirasSerasa_PendenciasPagamentoPF',
 'pessoa_anotacoesFinanceirasSerasa_AcoesJudiciaisPF',
 'pessoa_anotacoesFinanceirasSerasa_ProtestosPF',
 'pessoa_anotacoesFinanceirasSerasa_DividasVencidasPF',
 'pessoa_anotacoesFinanceirasSerasa_ChequesSemFundosPF',
 'pessoa_valorTotalAcaoJudicial',
 'pessoa_scores_HVA4',
 'pessoa_ratings_HVA4',
 'pessoa_scores_BVS_CUSTOM',
 'pessoa_scores_BLEND3_3',
 'pessoa_ratings_BVS_CUSTOM',
 'pessoa_ratings_BLEND3_3',
 'pessoa_scores_BLEND3_4',
 'pessoa_ratings_BLEND3_4',
 'pessoa_anotacoesFinanceirasSerasa',
 'pessoa_scores_BVS_CUSTOM_V2',
 'pessoa_scores_HFT1',
 'pessoa_ratings_BLEND_4',
 'pessoa_ratings_BVS_CUSTOM_V2',
 'pessoa_ratings_HFT1',
 'pessoa_scores_BLEND_REGRESSAO_2026',
 'pessoa_ratings_BLEND_REGRESSAO_2026',
 'request_matchmaking_on',
 'request_imovel_codigo_cidade_ibge',
 'request_pessoa_principal_nome',
 'request_principalDocument',
 'request_imobiliariaId',
 'request_idExterno',
 'request_rating',
 'rental_value',
 'request_modeloBlend',
 'request_rendaConsideradaContrato',
 'request_valorRestricaoTotal',
 'request_quantidadeRestricoesContrato',
 'request_nome',
 'request_dtNascimento',
 'request_situacaoCadastralSerasa',
 'request_existeErroPowerCurve',
 'request_scoreImobiliaria',
 'request_blendPredict',
 'request_restricoesPorModalidadeContrato',
 'request_valorTotalAcaoJudicial',
 'request_existingContractDebts_qtdeImoveis',
 'request_existingContractDebts_qtdeDividas',
 'request_existingContractDebts_saldoReceber',
 'request_existingContractDebts_taxaCredpago',
 'request_scores_BVS_CUSTOM_V2',
 'request_scores_HFT1',
 'request_blend3Variables_hasPreviousContracts',
 'request_blend3Variables_hadOverdueInvoiceInPreviousContracts',
 'request_blend3Variables_cityPc4HistoryOver100Contracts',
 'request_blend3Variables_realEstatePc4HistoryOver100Contracts',
 'request_fallbackPolicyResult_status',
 'request_fallbackPolicyResult_decision',
 'request_ratingPoliciesResult_status',
 'request_ratingPoliciesResult_decision',
 'property_type',
 'request_ratingPoliciesResult',
 'request_fallbackPolicyResult',
 'qtde_pefin',
 'valor_pefin_total',
 'modalidades_pefin',
 'REGRA_BLEND_4',
 'SCORE_BVS',
 'SCORE_SERASA',
 'RENDA',
 'income_commitment',
 'city_pc4_mais_100_contratos__pc_categorias_is_null',
 'agency_pc4_mais_100_contratos__pc_categorias_is_null',
 'score_proposto__bvs__normalized4_1',
 'SERASA_CHSV5__normalized4_1',
 'age__normalized4_1',
 'qtde_restricoes__consulta_realizada__normalized4_1',
 'income_commitment__normalized4_1',
 'agency_pc4_mais_100_contratos__pc_categorias__normalized4_1',
 'city_pc4_mais_100_contratos__pc_categorias__normalized4_1',
 'pred_blend4_1',
 'pred_blend4_1_to_score',
 'rating_manual_blend4',
 'rating_json_blend4',
 'rating_cl_pol_blend4']

In [19]:
df_blend4_dev[df_blend4_dev["contract_id"]==4358668][["contract_id", "model", "message_decisao", "message_scores_HVA4", "message_ratings_BVS_CUSTOM", "pessoa_scores_HVA4"]]

Empty DataFrame
Columns: [contract_id, model, message_decisao, message_scores_HVA4, message_ratings_BVS_CUSTOM, pessoa_scores_HVA4]
Index: []

In [20]:
df_funil[df_funil["is_fallback"]==1]

,contract_id,dt_lead,requested_at,iniciada_at,enviada_at,activated_at,cancelled_at,dt_saida,tipo_contrato,product_nm,...,lead_elegivel,proposta_iniciada,proposta_enviada,proposta_aprovada,proposta_ativada,is_activeted,first_comunicacao_date,first_competencia_date,rating_cl_pol_blend4,rating_pol_blend4
31,4508104,2026-08-13,2026-08-13,NaT,NaT,NaT,2026-08-13,NaT,PF,None,...,False,False,False,False,False,False,NaT,NaT,None,N/I
158,4491067,2026-08-10,2026-08-10,NaT,NaT,NaT,2026-09-10,NaT,PF,None,...,True,False,False,False,False,False,NaT,NaT,None,N/I
175,4487507,2026-08-10,2026-08-10,2026-08-10,2026-08-17,NaT,NaT,NaT,PF,Fit+,...,True,True,True,True,False,False,NaT,NaT,None,N/I
286,4497152,2026-08-11,2026-08-11,NaT,NaT,NaT,2026-09-11,NaT,PF,None,...,True,False,False,False,False,False,NaT,NaT,None,N/I
345,4526363,2026-08-18,2026-08-18,NaT,NaT,NaT,2026-09-18,NaT,PF,None,...,True,False,False,False,False,False,NaT,NaT,None,N/I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495838,4383404,2026-07-16,2026-07-16,NaT,NaT,NaT,2026-07-16,NaT,PF,None,...,False,False,False,False,False,False,NaT,NaT,None,N/I
495841,4384342,2026-07-16,2026-07-16,NaT,NaT,NaT,2026-07-16,NaT,PF,None,...,False,False,False,False,False,False,NaT,NaT,None,N/I
495844,4383637,2026-07-16,2026-07-16,NaT,NaT,NaT,2026-07-16,NaT,PF,None,...,False,False,False,False,False,False,NaT,NaT,None,N/I
495853,4383900,2026-07-16,2026-07-16,NaT,NaT,NaT,2026-08-16,NaT,PF,None,...,True,False,False,False,False,False,NaT,NaT,None,N/I
495859,4383529,2026-07-16,2026-07-16,NaT,NaT,NaT,2026-08-16,NaT,PF,None,...,True,False,False,False,False,False,NaT,NaT,None,N/I

In [21]:
df_funil.groupby("qtd_proponentes", dropna=False).size()

qtd_proponentes
1       374488
2        15601
3         1457
4          196
5           23
6            1
8            1
<NA>    104109
dtype: int64

In [22]:
df_funil.columns

Index(['contract_id', 'dt_lead', 'requested_at', 'iniciada_at', 'enviada_at',
       'activated_at', 'cancelled_at', 'dt_saida', 'tipo_contrato',
       'product_nm', 'modeloBlend', 'bureau_nm', 'modelo_blend',
       'bureau_nm_ajust', 'is_fallback', 'total_rental_value_informed_nr',
       'rental_value_nr', 'agency_id', 'contract_city_nm', 'person_age',
       'qtd_proponentes', 'score_imobiliaria',
       'person_restriction_total_value', 'bvs_cust_score_nr',
       'blend_regressao_predict_nr', 'rating_score_ds', 'person_deemed_income',
       'pre_analysis_result', 'lead_elegivel', 'proposta_iniciada',
       'proposta_enviada', 'proposta_aprovada', 'proposta_ativada',
       'is_activeted', 'first_comunicacao_date', 'first_competencia_date',
       'rating_cl_pol_blend4', 'rating_pol_blend4'],
      dtype='object')

In [23]:
df_funil[df_funil["qtd_proponentes"].isna()].groupby("modeloBlend", dropna=False).size()

modeloBlend
BLEND3_3                36208
BLEND3_4                24990
BLEND_4                 42332
BLEND_REGRESSAO_2026      389
BVS_CUSTOM_V2              57
HFT1                       26
NaN                       107
dtype: int64